# Numpy <hr></hr>

<b> Mark Ian O. Esique</b>
<br>Computer Engineer

# 1D Array

In [1]:
# imports and packages
import numpy as np

In [2]:
my_array = [1,2,3]  

In [3]:
my_array

[1, 2, 3]

In [4]:
array_name = np.array
my_array = np.array([1,2,3,])

In [5]:
np.shape(my_array)

(3,)

# 2D Array

In [6]:
my_array = np.array([
    [1,2,3],
    [4,5,6]
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
np.shape(my_array)

(2, 3)

In [8]:
trans_array = my_array.T

In [9]:
np.shape(my_array)

(2, 3)

In [10]:
trans_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [11]:
np.shape(trans_array)

(3, 2)

In [12]:
np.sum(trans_array,axis=0)

array([ 6, 15])

In [13]:
np.sum(trans_array,axis=1)

array([5, 7, 9])

# Measure of Central tendency

In [15]:
resistance = np.array([
    [10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8], #Jaguar
    [10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1,np.nan] #Panther
])

In [16]:
np.nanmean(resistance,axis=1)

array([ 9.4 , 10.75])